### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by fakezeta** [Mintplex-Labs/anything-llm#1007]
### How are you running AnythingLLM?

Docker (local)

### What happened?

mintplexlabs/anythingllm:master DIGEST sha256:3f51ee794b9c1bfb51285d564e5c08d4bbb759affda6885cd570999ab3fdf802

**Environment, CPU architecture, OS, and Version:**
linux/amd64 on Linux debian 12 host, docker version 24.0.7

Docker compose file:
```
version: "3.9"

services:
  anything-llm:
    container_name: anything-llm
    image: mintplexlabs/anythingllm:latest
    cap_add:
      - SYS_ADMIN
    volumes:
      - storage:/app/server/storage
      - hotdir:/app/collector/hotdir
      - outputs:/app/collector/outputs
      - /var/lib/docker/volumes/llm_storage/_data/.env:/app/server/.env
    environment:
      - STORAGE_DIR:"/app/server/storage"
    ports:
      - "3001:3001"

volumes:
  storage:
  hotdir:
  outputs:
```

**Describe the bug**
After pulling new image AnythingLLM container does not start. Error from logs:
```
node:internal/validators:162
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1097:7)
    at Object.<anonymous> (/app/collector/utils/comKey/index.js:8:12)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.19.1
```
**Additional context**

Working fine on old image
