### ISSUE TITLE
[BUG]: Unable to start docker containers - node errors

### ISSUE THREAD

**Issue by arsaboo** [Mintplex-Labs/anything-llm#1013]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Here's my docker compose file:
```yaml
version: "3.9"
services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    ports:
      - "3001:3001"
    cap_add:
      - SYS_ADMIN
    volumes:
      - "/mnt/docker/containers/anythingllm/:/app/server/storage"
```
But, I get this error when I start the container. 

```bash
node:internal/validators:162
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Object.resolve (node:path:1097:7)
    at Object.<anonymous> (/app/collector/utils/comKey/index.js:8:12)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Node.js v18.19.1
```

Both `node` and `yarn` are installed. 
```bash
$node --version
v18.20.0
$ yarn --version
1.22.22
```
