### ISSUE TITLE
[BUG]: Copy and copy code buttons don't work when locally deployed via docker

### ISSUE THREAD

**Issue by ovizii** [Mintplex-Labs/anything-llm#1136]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I asked a question which involved code (I was just testing if the code formatting works hence the simple question) and noticed that neither the copy button nor the copy code button work. 

I checked that it's not a browser problem by testing different browsers. 

None of these two buttons work:

![image](https://github.com/Mintplex-Labs/anything-llm/assets/837902/6e2f9a23-310a-474e-903b-de3b39b4f57c)

The one on the left actually changes and says copy when pressed but still does not actually copy anything:

![image](https://github.com/Mintplex-Labs/anything-llm/assets/837902/3e4b7a22-e625-4c38-8602-9c16dedc631d)

### Are there known steps to reproduce?

Right now, I used this image in my compose file:
`image: mintplexlabs/anythingllm:latest`

This is my compose file:

```
services:

# https://github.com/Mintplex-Labs/anything-llm/tree/master
# https://docs.useanything.com/

  anything-llm:
    image: mintplexlabs/anythingllm:latest
    container_name: anything-llm
    hostname: anything-llm
    cap_add:
      - SYS_ADMIN
    environment:
      - STORAGE_DIR=$STORAGE_DIR
    volumes:
      - "./.env:/app/server/.env"
      - "./storage:/app/server/storage"
    user: "1000:1000"
    ports:
      - "3101:3001"
    env_file:
      - .env
    cpus: 2
    mem_limit: 4G
```
