### ISSUE TITLE
[Docs]: Docker - how to use non-default port

### ISSUE THREAD

**Issue by chrisbennight** [Mintplex-Labs/anything-llm#1206]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Docker healthcheck fails when setting alternate SERVER_PORT in .env

this line:  https://github.com/Mintplex-Labs/anything-llm/blob/d72f1af36193200f71f5f0e52aef3d68204cc535/docker/docker-healthcheck.sh#L4

should be updated and the hardcoded 3001 replaced with SERVER_PORT if it is set
ref: https://github.com/Mintplex-Labs/anything-llm/blob/d72f1af36193200f71f5f0e52aef3d68204cc535/docker/.env.example#L1

### Are there known steps to reproduce?

set SERVER_PORT in the env file or environment to a port other than  3001

**Comment by krishhh16** [comment]
Hey @chrisbennight , I tried to reproduce this bug by changing the .env file and then running the docker-healthcheck.sh file. But apparently it seems to be working pretty fine on my side.

Could you please provide a better way to reproduce the problem that you are facing?

**Comment by timothycarambat** [comment]
Thanks @krishhh16

**Comment by chrisbennight** [comment]
@krishhh16 

The application still works, but docker sees the state of the app as unhealthy - a `docker ps | grep anything`  (replace anything with your container name if it's different) will show the unhealthy state.  So if you were checking by going to the webpage it works fine - it's just reporting the wrong thing to docker

(which makes sense because the healthcheck is hard coded to port 3001 - if that's changed (by setting SERVER_PORT) then nothing responds to the healthcheck.


The app works, but docker think's it's down, so using automations like autoheal, etc have bad interactions

Example docker output with docker compose below it (setting port to 3009 via env)

```
user@server:~$ docker ps | grep any
4ddff5f3ee12   mintplexlabs/anythingllm:latest                           "/bin/bash /usr/loca…"   5 minutes ago   Up 5 minutes (unhealthy)   3001/tcp, 0.0.0.0:3009->3009/tcp, :::3009->3009/tcp                                                                               anything-llm                                                                                        anything-llm
```

Where it says `unhealthy` it should say `healthy` (which it does if SERVER_PORT  is left at 3001)

the above is with: 
```
version: "3.9"
name: anythingllm
services:
  anything-llm:
    container_name: anything-llm
    image: mintplexlabs/anythingllm:latest
    cap_add:
      - SYS_ADMIN
    volumes:
      - "allm-storage:/app/server/storage"
      - "allm-hotdir:/app/collector/hotdir"
      - "allm-outputs:/app/collector/outputs"
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3009:3009"
    environment:
      - SERVER_PORT=3009
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  allm-storage:
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=nas.address,rw"
      device: ":/volume1/docker2/anything_llm/storage"
  allm-hotdir:
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=nas.address,rw"
      device: ":/volume1/docker2/anything_llm/hotdir"
  allm-outputs:
    driver_opts:
      type: "nfs"
      o: "nfsvers=4,addr=nas.address,rw"
      device: ":/volume1/docker2/anything_llm/outputs"
```

Does this help?
