### ISSUE TITLE
[FEAT]: Flatpak package for Linux

### ISSUE THREAD

**Issue by imbev** [Mintplex-Labs/anything-llm#1374]
### What would you like to see?

Given dependency problems such as #898 and additional setup required to use Appimages, I suggest the building and publication of a Flatpak package to Flathub. Unlike Appimage, Flatpak "just works" on the vast majority of Linux distributions and is often available OOTB in distribution graphical app stores.

**Comment by timothycarambat** [comment]
The issue with the AppImage is that when the AppImage mounts, it mounts to a temp directory and that directory is read-only, but often the prisma engine needs to download for the users OS. This fails, which then fails to run the migration and client generation, which then prevents some commands from saving due to the old primsa client not knowing about new fields and preventing updates on specific columns.

If on launch, flatpak does the same, this will not resolve the issue. I have never used flatpak though

**Comment by imbev** [comment]
Flatpak has a completely different approach to building and distribution from Appimage. See https://docs.flatpak.org/

I've created a manifest that almost works, but has a permission problem. Someone more experienced with Flatpak can probably complete it. Another issue with this manifest is that it allows the network permission to allow the prisma openssl download, so the prisma issue will need to be solved before publishing to Flathub.

```yaml
id: com.useanything.AnythingLLMDesktop
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.node18
command: entrypoint.sh
finish-args:
  - --share=ipc
  - --socket=x11
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --share=network
  #- --filesystem=xdg-documents
modules:
  - name: entrypoint.sh
    buildsystem: simple
    build-commands:
      - install -D entrypoint.sh /app/bin/entrypoint.sh
    sources:
      - type: file
        path: entrypoint.sh
  - name: anythingllmdesktop
    buildsystem: simple
    build-commands:
      - chmod +x *.AppImage && ./AnythingLLMDesktop.AppImage --appimage-extract
      - cd squashfs-root/resources/backend/ && node node_modules/prisma generate
      - mkdir -p /app/anythingllmdesktop
      - cp -r squashfs-root/* /app/anythingllmdesktop
    sources:
      - type: file
        url: https://web.archive.org/web/20240512181948/https://s3.us-west-1.amazonaws.com/public.useanything.com/latest/AnythingLLMDesktop.AppImage
        sha256: 792278729c870b4db3a2fd6512aee1d81e4130c1d5876d5df7e93b16bc97db65
  - name: zypak
    sources:
      - type: git
        url: https://github.com/refi64/zypak
        tag: v2024.01.17
build-options:
  append-path: /usr/lib/sdk/node18/bin
  build-args:
    - --share=network
```

```bash
#!/bin/sh
zypak-wrapper /app/anythingllmdesktop/AppRun
```
