### ISSUE TITLE
[DOCS]: Basic k8s kubernetes manifest. 

### ISSUE THREAD

**Issue by atljoseph** [Mintplex-Labs/anything-llm#1463]
### Description

Thanks for the docs about deploying to various hosting providers. Can you add a little pixie dust outlining some k8s deployment specs? Docker docs help for sure, but would be cool to have a template.

**Comment by timothycarambat** [comment]
I'd have to delegate this to someone in the community who has more experience with doing this. We can add it to the [community templates](https://github.com/Mintplex-Labs/anything-llm/tree/master/cloud-deployments)

**Comment by atljoseph** [comment]
I'll post something here later today... Figured it out

**Comment by atljoseph** [comment]
Expect pr today actually. Lost some time to aws ebs drivers.

**Comment by atljoseph** [comment]
We were able to make it work mostly, but something is driving me absolutely crazy.
If there really is no example in the repo already, then that likely means this hasn't been done yet.
In that case, I'll list the manifest that we have aas well as the symptoms.
Hoping for a quick resolution, as this is a value-add all-around.

```
---
apiVersion: v1                                                                                                                                           
kind: PersistentVolume                                                                                                                                   
metadata:                                                                                                                                                
  name: anything-llm-volume                                                                                                                              
  annotations:                                                                                                                                           
    pv.beta.kubernetes.io/uid: "1000"                                                                                                                    
    pv.beta.kubernetes.io/gid: "1000"                                                                                                                    
spec:                                                                                                                                                    
  storageClassName: gp2                                                                                                                                  
  capacity:                                                                                                                                              
    storage: 5Gi                                                                                                                                        
  accessModes:                                                                                                                                           
    - ReadWriteOnce                                                                                                                                      
  awsElasticBlockStore:                                                                                                                                  
    volumeID: ec2-ebs-volume-uuid-from-aws-console                                                                                                                           
    fsType: ext4
  nodeAffinity:                                                                                                                                          
    required:                                                                                                                                            
      nodeSelectorTerms:                                                                                                                                 
      - matchExpressions:                                                                                                                                
        - key: topology.kubernetes.io/zone                                                                                                               
          operator: In                                                                                                                                   
          values:                                                                                                                                        
          - us-direction-123  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anything-llm-volume-claim
  namespace: "{{ namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anything-llm
  namespace: "{{ namespace }}"
  labels:
    anything-llm: "true"
spec:
  selector:
    matchLabels:
      k8s-app: anything-llm
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        anything-llm: "true"
        k8s-app: anything-llm
        app.kubernetes.io/name: anything-llm
        app.kubernetes.io/part-of: anything-llm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
    spec:
      serviceAccountName: "default"
      terminationGracePeriodSeconds: 10
      securityContext:                                                                                                                                                              
        fsGroup: 1000
        runAsNonRoot: true                                                                                                                                                          
        runAsGroup: 1000
        runAsUser: 1000
      affinity:                                                                                                                                                                                                                                                                          
        nodeAffinity:                                                                                                                                                                                                                                                                    
          requiredDuringSchedulingIgnoredDuringExecution:                                                                                                                                                                                                                                
            nodeSelectorTerms:                                                                                                                                                                                                                                                           
            - matchExpressions:                                                                                                                                                                                                                                                          
              - key: topology.kubernetes.io/zone                                                                                                                                                                                                                                         
                operator: In                                                                                                                                                                                                                                                             
                values:                                                                                                                                                                                                                                                                  
                - us-direction-123  
      containers:
      - name: anything-llm
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        imagePullPolicy: IfNotPresent
        image: "mintplexlabs/anythingllm:master"
        securityContext:                     
          allowPrivilegeEscalation: true                                                                                                                                                                                                                                                 
          capabilities:                                                                                                                                                                                                                                                                  
            add:                                                                                                                                                                                                                                                                         
              - SYS_ADMIN                                                                                                                                                                                                                                                                
          runAsNonRoot: true                                                                                                                                                                                                                                                             
          runAsGroup: 1000                                                                                                                                                                                                                                                               
          runAsUser: 1000                                                                                                                                       
        command: # Specify a command to override the Dockerfile's ENTRYPOINT.
          - /bin/bash
          - -c
          - |
            # Some debug stuff...
            set -x -e
            sleep 3
            echo "AWS_REGION: $AWS_REGION"
            echo "SERVER_PORT: $SERVER_PORT"
            echo "NODE_ENV: $NODE_ENV"
            echo "STORAGE_DIR: $STORAGE_DIR"
            # The following was taken from the Dockerfile's ENTRYPOINT, since `command` overrides that.
            {
              cd /app/server/ &&
                npx prisma generate --schema=./prisma/schema.prisma &&
                npx prisma migrate deploy --schema=./prisma/schema.prisma &&
                node /app/server/index.js
              echo "Server process exited with status $?"
            } &
            { 
              node /app/collector/index.js
              echo "Collector process exited with status $?"
            } &
            wait -n
            exit $?
        readinessProbe:
          httpGet:
            path: /v1/api/health
            port: 8888
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 2
        livenessProbe:
          httpGet:
            path: /v1/api/health
            port: 8888
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
        env:
          - name: AWS_REGION
            value: "{{ aws_region }}"
          - name: AWS_ACCESS_KEY_ID
            value: "{{ aws_access_id }}"
          - name: AWS_SECRET_ACCESS_KEY
            value: "{{ aws_access_secret }}"
          - name: SERVER_PORT
            value: "3001"
          - name: JWT_SECRET
            value: "my-random-string-for-seeding" # Please generate random string at least 12 chars long.
          - name: VECTOR_DB
            value: "lancedb"
          - name: STORAGE_DIR
            # value: "/data"
            value: "/app/server/storage"
          - name: NODE_ENV
            value: "development"
          - name: UID
            value: "1000"
          - name: GID
            value: "1000"
        volumeMounts: 
          - name: anything-llm-server-storage-volume-mount
            # mountPath: /data                                                                                                                                                  
            mountPath: /app/server/storage                                                                                                                                                  
      volumes:
        - name: anything-llm-server-storage-volume-mount
          persistentVolumeClaim:
            claimName: anything-llm-volume-claim
```

============
Symptoms: (Apologies if this is confusing. I am confused LOL)
============

Have dialed everything in, but getting conflicting outcomes when changing these settings:
- NODE_ENV, Values attempted: production, development
- STORAGE_DIR, Values attempted: (not set), /data, /app/server/storage

In general, when the Persistent Volume is mounted to same dir as STORAGE_DIR (/app/server/storage):
- The app does not "see" everything else in /app/server/storage.
- Mounting the persistent volume seems to mask what was there already in the image.
- We don't want to use this path in the end ... just a note for completeness.

When STORAGE_DIR is not set:
- It works perfectly, just nothing is persisted across pod restarts.
- HTTPS works perfectly.

When NODE_ENV=production, no matter the value of STORAGE_DIR:
- Site loads perfectly, nut chat workspaces do not persist.
- Can't seem to set STORAGE_DIR to anything... It keeps demanding on using /app/server/storage (IS QUITE ANNOYING).
- Confirmed that it is ignoring the setting - exec-ed into the container, and confirming contents of folders and timestamps.

When NODE_ENV=development & STORAGE_DIR=/data:
- Exec into the container shows the correct database has last been touched... The one in our custom directory, and not the one in the docker image. **Woohoo!** That means that things will persist as expected.
- There is a Not Found message when accessing the site (hosted in cluster on http, and ingress wraps it with https). I see that in /data, everything is a later timestamp that in /app/server/storage... EXCEPT with the `comkey` directory.

Lastly, I cannot get this thing to forget the admin setup was performed, even after clearing all data from the persistent volume and doing rollout restart.

This is super frustrating LOL, and that is a lot of info.

But, it seems like some of the build code and structural aspects of the app might not play 100% nicely with k8s.
- Its almost there, but not quite.

Anyways, I've spent 2 days on this, and I'm out of energy. Would LOVE to be able to use it.

@timothycarambat

**Comment by timothycarambat** [comment]
@atljoseph How do you use these templates? I don't use Kubernetes so I'm unsure how to even debug. For what it is worth, it may make sense to use modify
> image: "mintplexlabs/anythingllm:master"

to `image: "mintplexlabs/anythingllm:render"`. This image is special in that it pins all storage to have a mounted EBS attached to `/storage`. This is how we do persistent storage on Render and Railway because of the STORAGE_DIR flexibility that needs to exist for the Docker image, but cannot be so easily configured in ephemeral storage ecosystems (like K8) where containers spin up/down and get destroyed/created on the fly.

**Comment by atljoseph** [comment]
Thanks @timothycarambat I'll try that. 
Curious, how do i reset everything?
Doesn't seem to ever go back to the onboarding.
It would revert back to onboarding early on, but can't get it to do that anymore.
So, if you could tell me more about where all that is stored, it might help track down the issue.

**Comment by atljoseph** [comment]
It would be nice to be able to set Admin user through ENV Vars, or at least have the option to.

**Comment by atljoseph** [comment]
OK, this worked grrrrreat!!!! 

The `render` image tag worked as expected.

Final product:
```
---
apiVersion: v1                                                                                                                                           
kind: PersistentVolume                                                                                                                                   
metadata:                                                                                                                                                
  name: anything-llm-volume                                                                                                                              
  annotations:                                                                                                                                           
    pv.beta.kubernetes.io/uid: "1000"                                                                                                                    
    pv.beta.kubernetes.io/gid: "1000"                                                                                                                    
spec:                                                                                                                                                    
  storageClassName: gp2                                                                                                                                  
  capacity:                                                                                                                                              
    storage: 5Gi                                                                                                                                        
  accessModes:                                                                                                                                           
    - ReadWriteOnce                                                                                                                                      
  awsElasticBlockStore:    
    # This is the volumne UUID from AWS EC2 EBS Volumes list.                                                                                                                              
    volumeID: "{{ anythingllm_awsElasticBlockStore_volumeID }}"                                                                                                                           
    fsType: ext4
  nodeAffinity:                                                                                                                                          
    required:                                                                                                                                            
      nodeSelectorTerms:                                                                                                                                 
      - matchExpressions:                                                                                                                                
        - key: topology.kubernetes.io/zone                                                                                                               
          operator: In                                                                                                                                   
          values:                                                                                                                                        
          - us-east-1c  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anything-llm-volume-claim
  namespace: "{{ namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anything-llm
  namespace: "{{ namespace }}"
  labels:
    anything-llm: "true"
spec:
  selector:
    matchLabels:
      k8s-app: anything-llm
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        anything-llm: "true"
        k8s-app: anything-llm
        app.kubernetes.io/name: anything-llm
        app.kubernetes.io/part-of: anything-llm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
    spec:
      serviceAccountName: "default"
      terminationGracePeriodSeconds: 10
      securityContext:                                                                                                                                                              
        fsGroup: 1000
        runAsNonRoot: true                                                                                                                                                          
        runAsGroup: 1000
        runAsUser: 1000
      affinity:                                                                                                                                                                                                                                                                          
        nodeAffinity:                                                                                                                                                                                                                                                                    
          requiredDuringSchedulingIgnoredDuringExecution:                                                                                                                                                                                                                                
            nodeSelectorTerms:                                                                                                                                                                                                                                                           
            - matchExpressions:                                                                                                                                                                                                                                                          
              - key: topology.kubernetes.io/zone                                                                                                                                                                                                                                         
                operator: In                                                                                                                                                                                                                                                             
                values:                                                                                                                                                                                                                                                                  
                - us-east-1c  
      containers:
      - name: anything-llm
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        imagePullPolicy: IfNotPresent
        image: "mintplexlabs/anythingllm:render"
        securityContext:                     
          allowPrivilegeEscalation: true                                                                                                                                                                                                                                                 
          capabilities:                                                                                                                                                                                                                                                                  
            add:                                                                                                                                                                                                                                                                         
              - SYS_ADMIN                                                                                                                                                                                                                                                                
          runAsNonRoot: true                                                                                                                                                                                                                                                             
          runAsGroup: 1000                                                                                                                                                                                                                                                               
          runAsUser: 1000                                                                                                                                       
        command: 
          # Specify a command to override the Dockerfile's ENTRYPOINT.
          - /bin/bash
          - -c
          - |
            set -x -e
            sleep 3
            echo "AWS_REGION: $AWS_REGION"
            echo "SERVER_PORT: $SERVER_PORT"
            echo "NODE_ENV: $NODE_ENV"
            echo "STORAGE_DIR: $STORAGE_DIR"
            {
              cd /app/server/ &&
                npx prisma generate --schema=./prisma/schema.prisma &&
                npx prisma migrate deploy --schema=./prisma/schema.prisma &&
                node /app/server/index.js
              echo "Server process exited with status $?"
            } &
            { 
              node /app/collector/index.js
              echo "Collector process exited with status $?"
            } &
            wait -n
            exit $?
        readinessProbe:
          httpGet:
            path: /v1/api/health
            port: 8888
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 2
        livenessProbe:
          httpGet:
            path: /v1/api/health
            port: 8888
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
        env:
          - name: AWS_REGION
            value: "{{ aws_region }}"
          - name: AWS_ACCESS_KEY_ID
            value: "{{ aws_access_id }}"
          - name: AWS_SECRET_ACCESS_KEY
            value: "{{ aws_access_secret }}"
          - name: SERVER_PORT
            value: "3001"
          - name: JWT_SECRET
            value: "my-random-string-for-seeding" # Please generate random string at least 12 chars long.
          - name: VECTOR_DB
            value: "lancedb"
          - name: STORAGE_DIR
            value: "/storage"
          - name: NODE_ENV
            value: "production"
          - name: UID
            value: "1000"
          - name: GID
            value: "1000"
        volumeMounts: 
          - name: anything-llm-server-storage-volume-mount
            mountPath: /storage                                                                                                                                                  
      volumes:
        - name: anything-llm-server-storage-volume-mount
          persistentVolumeClaim:
            claimName: anything-llm-volume-claim
---
# This serves the UI and the backend.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anything-llm-ingress
  namespace: "{{ namespace }}"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ namespace }}-chat.{{ base_domain }}"
    kubernetes.io/ingress.class: "internal-ingress"
    nginx.ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: "{{ namespace }}-chat.{{ base_domain }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: anything-llm-svc
            port: 
              number: 3001
  tls: # < placing a host in the TLS config will indicate a cert should be created
    - hosts:
        - "{{ namespace }}-chat.{{ base_domain }}"
      secretName: letsencrypt-prod
---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: anything-llm
  name: anything-llm-svc
  namespace: "{{ namespace }}"
spec:
  ports:
  # "port" is external port, and "targetPort" is internal.
  - port: 3301
    targetPort: 3001
    name: traffic
  - port: 9090
    targetPort: 9090
    name: metrics
  selector:
    k8s-app: anything-llm
```

@timothycarambat This is what is known as a kubernetes "manifest". 
We don't use Kustomize, so this would have to be adapted for anyone who uses that (I don't understand it).
With Helm, we use the "render" function to apply variables that are loaded per environment.
Our Helm repo is too large just to extract a full working filesystem example here, sorry.
But, essentially... Variables are placed in handlebars, and then replaced at render time.
`someK8sConfigValue: "{{ willBeReplacedAtRender }}"`
So, anyone can fill in their values, and apply this directly to their cluster.
I did not include an ingress, because different folks use different strokes, depending on their needs.

Examples:
- namespace: "default" would work for someone's homelab. They'll know what they need to use if not default.
- aws variables: Well, these are required for AWS. AWS users will know and love them.
- anythingllm_awsElasticBlockStore_volumeID: This is the volume UUID from AWS EC2 EBS Volumes list.

**Comment by atljoseph** [comment]
Hoping this helps someone else !

**Comment by atljoseph** [comment]
Getting an error and empty scrren when visiting LLM Preferences from Settings.

<img width="1718" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/25017621/aeb517b3-1eec-4a0b-a308-e9864505e97a">

<img width="1188" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/25017621/3b09b137-9b23-484b-8a56-688a4cc11e67">

**Comment by atljoseph** [comment]
<img width="977" alt="image" src="https://github.com/Mintplex-Labs/anything-llm/assets/25017621/be461f92-b34d-4e33-8070-c6341d89392f">

**Comment by atljoseph** [comment]
I think this needs a way for Admin to reset everything from the frontend.

**Comment by atljoseph** [comment]
> You can also just rm -rf /host/storage/anythingllm.db && touch /host/storage/anythingllm.db to delete and recreate an empty db
Did that... All the chat workspaces were cleared out...
- But on reload was still signed in as the admin user.

Does that mean the users are not stored in anythingllm.db?
- I'm assuming this is just SQLite, right?

> Remove the LLM_PROVIDER, EMBEDDING_ENGINE and VECTOR_DB keys in the storage .env. 
None of these are set currently. At deploy/config time, we load ENV Vars from key-value store, and then apply the changes to kubernetes. We don't have an ENV file. Kubernetes supplies these, and if they are modified, they do not persist across restarts. 

> You can also reset the user db by yarn prisma:reset in the root or in /app/server when in docker container.
Can you tell me more about that, please? Where is this prisma DB stored? Looking to have a solution that does not involve exec-ing to an ephemeral container.

**Comment by timothycarambat** [comment]
@atljoseph that ENV error is because in 
```
 env:
          - name: AWS_REGION
            value: "{{ aws_region }}"
          - name: AWS_ACCESS_KEY_ID
            value: "{{ aws_access_id }}"
          - name: AWS_SECRET_ACCESS_KEY
            value: "{{ aws_access_secret }}"
          - name: SERVER_PORT
            value: "3001"
          - name: JWT_SECRET
            value: "my-random-string-for-seeding" # Please generate random string at least 12 chars long.
          - name: VECTOR_DB
            value: "lancedb"
          - name: STORAGE_DIR
            value: "/storage"
          - name: NODE_ENV
            value: "production"
          - name: UID
            value: "1000"
          - name: GID
            value: "1000"
```

You have  
```
- name: VECTOR_DB
  value: "lancedb"
```

Remove this key and you can onboard and that LLM preference bug wont appear. Onboarding set these vars

**Comment by atljoseph** [comment]
Thank you sir. Will try that tomorrow!

**Comment by atljoseph** [comment]
Worked. Everything above in my last message worked as expected, especially after removing that env var.

**Comment by reefland** [comment]
@atljoseph - In your templates `readinessProbe` and `livenessProbe` are using port `8888`, and while the logs report `Document processor app listening on port 8888` I'm unable to get curl to respond to that port, I have to CTRL-C to stop.:
```
[ root@curl:/ ]$ curl -v anything-llm.anything-llm:8888/v1/api/health
^C
```

I don't see how your probes could be successful. I instead use probes against port 3001:

```
[ root@curl:/ ]$ curl anything-llm.anything-llm:3001
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <link rel="icon" type="image/svg+xml" href="/favicon.png" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>AnythingLLM | Your personal LLM trained on anything</title>
...
```

And path doesn't matter. Seems to get same output no matter what you ask for.
```
[ root@curl:/ ]$ curl anything-llm.anything-llm:3001/blah/blah/blah
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <link rel="icon" type="image/svg+xml" href="/favicon.png" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>AnythingLLM | Your personal LLM trained on anything</title>
...
```

In regards to Prometheus metrics, you have annotations for scrapes to port 9090 and setup that port for the service, but there is nothing within the Anything-LLM container listening to that port that I could find.  If it doesn't exist that could be cleaned up.

I'd be curious to know why you needed to grant `allowPrivilegeEscalation: true` and grant SYS_ADMIN capabilities to the container:
```
       securityContext:                     
          allowPrivilegeEscalation: true                                                                                                                                                                                                                                                 
          capabilities:                                                                                                                                                                                                                                                                  
            add:                                                                                                                                                                                                                                                                         
              - SYS_ADMIN                                                                                                                                                                                                                                                                
          runAsNonRoot: true                                                                                                                                                                                                                                                             
          runAsGroup: 1000                                                                                                                                                                                                                                                               
          runAsUser: 1000
```

I find Anything-LLM runs OK, locked down a bit more at the container level:
```
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: false
```

Then at the Pod level you can do:
```
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
```

For others trying this.  The `.env` file concept does not work well with Kubernetes.   In Kubernetes this would be stored in a configMap and either mounted into the container's filesystem or the configMap values mapped to ENV variables. Being that some of the values are sensitive then these would be stored in a secret and mapped to ENV variables.

Trying to mount the `.env` file from a configMap works when `NODE_ENV='production'` is used, unfortunately Anything-llm tries to update its `.env` file in development mode which breaks and crashes as configMap is read-only.  Otherwise you have to do some silly trickery with an InitContainer where you could mount the `.env` file to something like `/tmp` and then use commands manually copy it to `/app/server/` directory to make it writeable (but changes not persisted) before the anything-llm container is started.
