### ISSUE TITLE
[BUG]: Bulk Link Scraper in docker version throws error

### ISSUE THREAD

**Issue by troymroberts** [Mintplex-Labs/anything-llm#2098]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

embedding a single page works fine. Embedding via the bulk link scraper doesn't work. Receive the following errors in the log

[collector] info: Discovering links...
[collector] error: Failed to get page links from https://learn.microsoft.com/en-us/azure/well-architected/reliability. Error: Failed to launch the browser process!
[1006:1006:0810/184605.831237:FATAL:zygote_host_impl_linux.cc(127)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.

**Comment by shatfield4** [comment]
When did you pull the docker image for this? We just pushed an update a few hours ago to the bulk link scraper and I want to verify if that is what's causing the issue or not.

**Comment by timothycarambat** [comment]
@shatfield4  This is not the case. The issue @troymroberts is having is that they have run the docker container without the `--cap-add SYS_ADMIN` as defined in our documentation in all places. Without this param the puppeteer process cannot safely run a sandbox chrome process
https://docs.anythingllm.com/installation/self-hosted/local-docker#recommend-way-to-run-dockerized-anythingllm

**Comment by troymroberts** [comment]
> @shatfield4 This is not the case. The issue @troymroberts is having is that they have run the docker container without the `--cap-add SYS_ADMIN` as defined in our documentation in all places. Without this param the puppeteer process cannot safely run a sandbox chrome process https://docs.anythingllm.com/installation/self-hosted/local-docker#recommend-way-to-run-dockerized-anythingllm

This is correct, this was the issue. My apologies.

**Comment by coffeverton** [comment]
Hi, I'm also having this issue. The error message is the same. Can you help me?

```
anythingllm  | [collector] info: Found 1 links to scrape.
anythingllm  | [collector] info: Starting bulk scraping...
anythingllm  | [collector] info: Scraping 1/1: https://suporte.agencialink.com
anythingllm  | [collector] error: Failed to scrape https://suporte.agencialink.com. Error: Failed to launch the browser process!
anythingllm  | [179:179:1029/185118.583950:FATAL:zygote_host_impl_linux.cc(127)] No usable sandbox! Update your kernel or see https://chrom...
```

My docker-compose.yml is based on this one: https://github.com/Mintplex-Labs/anything-llm/blob/master/docker/HOW_TO_USE_DOCKER.md:

```
version: '3.8'
services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    ports:
      - "3007:3001"
    cap_add:
      - SYS_ADMIN
    environment:
    # Adjust for your environment
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET="f..."
      - EMBEDDING_ENGINE='openai'
      - OPEN_AI_KEY=sk-....
      - EMBEDDING_MODEL_PREF='text-embedding-ada-002'
      - VECTOR_DB=lancedb
      - WHISPER_PROVIDER="openai"
      - TTS_PROVIDER="openai"
      - PASSWORDMINCHAR=8
      # Add any other keys here for services or settings
      # you can find in the docker/.env.example file
      - DISABLE_TELEMETRY="true"
    volumes:
      - anythingllm_storage:/app/server/storage
    restart: always

volumes:
  anythingllm_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/storage
```
