### ISSUE TITLE
[BUG]: Could not validate login after updating docker container in CasaOS

### ISSUE THREAD

**Issue by Xoconoch** [Mintplex-Labs/anything-llm#2814]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

I am running a local server in a home lab using Debian 12 and CasaOS, installed AnythingLLM through the built-in App Store. After I updated from 1.6 to 1.7, now every time a user tries to log in, the page shows a message saying: "Error: Could not validate login".

With further testing, I found that this happens not only when one updates the container, but every time it is taken down and up with the respective docker CLI commands or through the CasaOS interface.

### Are there known steps to reproduce?

1. Have AnythingLLM installed in CasaOS
2. In the UI, click the three dots of AnythingLLM's icon and then the "Check then update"
3. Wait for the process to finish, then try to login with existing credentials

**Comment by timothycarambat** [comment]
Its because the storage volume is probably ephemeral to the container. You need to use the command on this page when launching the container or else everytime the container is destroyed its volume is too - which includes your JWT seed and all

https://docs.anythingllm.com/installation-docker/local-docker
```bash
export STORAGE_LOCATION=$HOME/anythingllm && \ # <-- this mounts storage between container reboots
mkdir -p $STORAGE_LOCATION && \
touch "$STORAGE_LOCATION/.env" && \
docker run -d -p 3001:3001 \
--cap-add SYS_ADMIN \
-v ${STORAGE_LOCATION}:/app/server/storage \
-v ${STORAGE_LOCATION}/.env:/app/server/.env \
-e STORAGE_DIR="/app/server/storage" \
mintplexlabs/anythingllm
```

**Comment by Xoconoch** [comment]
The service runs using docker compose, is there a way to include the proper configuration to the docker-compose.yml file?

**Comment by timothycarambat** [comment]
Does `/DATA/AppData/anythingllm/storage` exist on host filesystem? it should be populated with information and files like anythingllm.db and other folders.

```
volumes:
      - type: bind
        source: /DATA/AppData/anythingllm/storage
        target: /app/server/storage
```

I think what might be missing is the second volume mount command for the `.env` file 

`-v ${STORAGE_LOCATION}/.env:/app/server/.env `

```yaml
volumes:
      # binds folder
      - type: bind
        source: /DATA/AppData/anythingllm/storage # Binds to folder on host /DATA/AppData/anythingllm/storage
        target: /app/server/storage
      # binds env
      - type: bind
        source: /DATA/AppData/anythingllm/storage/.env # Maps .env in storage folder to correct place in image.
        target: /app/server/.env
````
