### ISSUE TITLE
[BUG]: Unable to Deploy in Portainer with Docker Compose

### ISSUE THREAD

**Issue by spencerthayer** [Mintplex-Labs/anything-llm#2821]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

I am encountering issues when deploying AnythingLLM exclusively via Portainer using the `docker-compose.yml` configuration. Despite following the instructions provided in the README, I am running into persistent errors:

1. **Mounting Issues**: Errors related to `.env` being mounted as a directory instead of a file. Logs show:
   ```
   OCI runtime create failed: runc create failed: error mounting "/appdata/anythingllm/.env" to rootfs at "/app/server/.env": not a directory.
   ```
2. **Port Configuration with Host Mode**: When using `network_mode: host`, the ports configuration seems to be discarded, as noted in the Portainer logs.

I expected the stack to deploy successfully with all required services running, accessible via `http://localhost:3001`.

### Are there known steps to reproduce?

1. Configure `docker-compose.yml` as outlined in the README:
   ```yaml
   version: "3.8"
   services:
     anythingllm:
       image: mintplexlabs/anythingllm
       container_name: anythingllm
       network_mode: host
       environment:
         - STORAGE_DIR=/app/server/storage
         - JWT_SECRET="secure-random-string"
         - LLM_PROVIDER=ollama
         - OLLAMA_BASE_PATH=http://127.0.0.1:11434
         - EMBEDDING_ENGINE=ollama
         - EMBEDDING_BASE_PATH=http://127.0.0.1:11434
         - VECTOR_DB=lancedb
       volumes:
         - /appdata/anythingllm/storage:/app/server/storage
         - /appdata/anythingllm/.env:/app/server/.env
       restart: always
   volumes:
     anythingllm_storage:
       driver: local
       driver_opts:
         type: none
         o: bind
         device: /appdata/anythingllm/storage
   ```
2. Deploy the stack in Portainer using the above configuration.
3. Observe the errors in Portainer logs:
   - Mounting `/appdata/anythingllm/.env` results in the container failing to initialize.
   - Network mode `host` discards the published ports.

---

### What I’ve Tried

1. Verified that `/appdata/anythingllm/.env` exists as a file:
   ```bash
   touch /appdata/anythingllm/.env
   chmod 600 /appdata/anythingllm/.env
   ```
2. Ensured `/appdata/anythingllm/storage` exists and has proper permissions:
   ```bash
   mkdir -p /appdata/anythingllm/storage
   chmod -R 777 /appdata/anythingllm/storage
   ```
3. Adjusted environment variables to match the provided examples.
4. Attempted using `http://172.17.0.1:11434` for `OLLAMA_BASE_PATH` as the container runs on Ubuntu.

---

### Additional Notes

I am specifically looking for a solution that works exclusively within Portainer, without relying on direct terminal commands after deployment. If there are additional steps or corrections required to adapt the setup for Portainer, please let me know. Any help in resolving these issues or updating the README for better clarity in Portainer deployments would be greatly appreciated. Thank you! 😊
