### ISSUE TITLE
[BUG]: LLM_PROVIDER doesn't work on .env docker compose

### ISSUE THREAD

**Issue by GeuntaBuwono** [Mintplex-Labs/anything-llm#3151]
### How are you running AnythingLLM?

Docker (local)

### What happened?

I've been running on docker-compose. 

whenever I change `LLM_PROVIDER` on .env and restart the docker-compose, it returns to OLLAMA, when I open the webpage config `/settings/llm-preference`.

here's .env config 
```
# Auto-dump ENV from system call on 12:50:57 GMT+0000 (Coordinated Universal Time)
LLM_PROVIDER='openrouter'
EMBEDDING_MODEL_PREF='nomic-embed-text:latest'
OLLAMA_BASE_PATH='http://127.0.0.1:11434'
OLLAMA_MODEL_PREF='llama2'
OLLAMA_MODEL_TOKEN_LIMIT='4096'
EMBEDDING_ENGINE='ollama'
EMBEDDING_BASE_PATH='http://127.0.0.1:11434'
EMBEDDING_MODEL_MAX_CHUNK_LENGTH='8192'
VECTOR_DB='lancedb'
...
```

here's my docker-compose.yml
```
name: anythingllm

networks:
  anything-llm:
    driver: bridge

services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        ARG_UID: ${UID:-1000}
        ARG_GID: ${GID:-1000}
    cap_add:
      - SYS_ADMIN
    volumes:
      - "./.env:/app/server/.env"
      - anythingllm_storage:/app/server/storage
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3010:3001"
    env_file:
      - .env
    networks:
      - anything-llm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
volumes:
  anythingllm_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./
```
