### ISSUE TITLE
[FEAT]: Admin section to edit CSS

### ISSUE THREAD

**Issue by severfire** [Mintplex-Labs/anything-llm#3212]
### What would you like to see?

Sometimes we need to change color scheme or hide some things.
This feature would be much helpful here.

**Comment by timothycarambat** [comment]
This is something that would be better suited on a fork of the software at this current time - supporting the nuance of color themes is quite far down in our backlog currently.

**Comment by scottybo** [comment]
@timothycarambat if we prepared a pull request for this, would you be open to considering it? I appreciate that it's low on the roadmap, but UI / UX is such an important part of adoption of a platform, and if we're trying to get people to switch from daily use of ChatGPT / Claude, it's my strong opinion that they need to have an experience which is on par with it.

I get that you guys are focusing on the technical side of things (and this is amazing!), but I do feel that the UI is getting left behind as a result.

Below is my proposal:

Add Support for Custom Themes via /storage/themes Directory

### Overview

Currently, AnythingLLM supports only default and light themes. This proposal adds support for custom themes through a structured `/storage/themes` directory, allowing users and the community to create and share themes.

### Proposed Directory Structure

```
/storage/themes/
├── cyberpunk/
│ ├── theme.css
│ ├── theme.json
│ └── assets/
│ ├── preview.png
│ └── icons/
├── dark-blue/
│ ├── theme.css
│ ├── theme.json
│ └── assets/
└── forest/
├── theme.css
├── theme.json
└── assets/
```

### Implementation Details

1. Update `useTheme` Hook (`frontend/src/hooks/useTheme.js`)

```javascript
import { REFETCH_LOGO_EVENT } from "@/LogoContext";
import { useState, useEffect } from "react";
const availableThemes = {
default: "Default",
light: "Light",
};
async function fetchCustomThemes() {
try {
const response = await fetch('/api/themes');
const { themes } = await response.json();
return themes.reduce((acc, theme) => {
acc[theme.id] = {
name: theme.name,
description: theme.description,
author: theme.author,
version: theme.version,
preview: theme.preview
};
return acc;
}, {});
} catch (error) {
console.error('Failed to fetch custom themes:', error);
return {};
}
}
export function useTheme() {
const [customThemes, setCustomThemes] = useState({});
useEffect(() => {
fetchCustomThemes().then(themes => {
setCustomThemes(themes);
if (theme && !themes[theme] && theme !== 'default' && theme !== 'light') {
setTheme('default');
}
});
}, []);
const [theme, setTheme] = useState(() => {
return localStorage.getItem("theme") || "default";
});
useEffect(() => {
document.documentElement.setAttribute("data-theme", theme);
document.body.classList.toggle("light", theme === "light");
const existingCustomTheme = document.getElementById('custom-theme');
if (existingCustomTheme) {
existingCustomTheme.remove();
}
if (theme !== 'default' && theme !== 'light') {
const link = document.createElement('link');
link.id = 'custom-theme';
link.rel = 'stylesheet';
link.href = /storage/themes/${theme}/theme.css;
document.head.appendChild(link);
}
localStorage.setItem("theme", theme);
window.dispatchEvent(new Event(REFETCH_LOGO_EVENT));
}, [theme]);
return {
theme,
setTheme,
availableThemes: { ...availableThemes, ...customThemes },
getThemeInfo: (themeId) => customThemes[themeId]
};
}
```

2. Add Backend Theme Endpoint (`backend/endpoints/themes.js`)

```javascript
const path = require('path');
const fs = require('fs').promises;
async function getThemes(req, res) {
try {
const themesDir = path.join(process.cwd(), 'storage', 'themes');
const directories = await fs.readdir(themesDir);
const themes = await Promise.all(
directories
.filter(async (dir) => {
const stat = await fs.stat(path.join(themesDir, dir));
return stat.isDirectory();
})
.map(async (dir) => {
const themeJsonPath = path.join(themesDir, dir, 'theme.json');
try {
const themeData = JSON.parse(
await fs.readFile(themeJsonPath, 'utf-8')
);
return {
id: dir,
name: themeData.name || dir,
description: themeData.description,
author: themeData.author,
version: themeData.version,
preview: /storage/themes/${dir}/assets/preview.png,
cssPath: /storage/themes/${dir}/theme.css
};
} catch (error) {
console.warn(No theme.json found for ${dir});
return {
id: dir,
name: dir.charAt(0).toUpperCase() + dir.slice(1),
cssPath: /storage/themes/${dir}/theme.css
};
}
})
);
res.json({ themes: themes.filter(Boolean) });
} catch (error) {
console.error('Error reading themes:', error);
res.status(500).json({ error: 'Failed to read themes' });
}
}
module.exports = { getThemes };
```

3. Example Theme Files

theme.json

```json

{
"name": "Cyberpunk",
"description": "A neon-inspired cyberpunk theme",
"version": "1.0.0",
"author": "Your Name",
"website": "https://yourwebsite.com",
"license": "MIT",
"colors": {
"primary": "#ff00ff",
"secondary": "#00ffff",
"background": "#0a0a0a"
}
}
```

theme.css

```css
/ Import any additional fonts /
@import url('https://fonts.googleapis.com/css2?family=Cyberpunk+Font&display=swap');
/ Theme variables /
:root[data-theme="cyberpunk"] {
--background-color: #0a0a0a;
--text-color: #00ffff;
--primary-color: #ff00ff;
--font-family: 'Cyberpunk Font', sans-serif;
}
/ Theme-specific overrides /
[data-theme="cyberpunk"] .some-specific-component {
/ Component-specific styles /
}
/ Theme assets can be referenced relative to the theme folder /
[data-theme="cyberpunk"] .themed-background {
background-image: url('./assets/background.png');
}
```

### Benefits

- Self-contained theme packages
- Easy theme sharing and distribution
- Support for theme metadata and assets
- Backwards compatible with existing themes
- Community-driven theme development

### Required Changes

- Create /storage/themes directory
- Add new backend endpoint for theme discovery
- Update theme context to support custom themes
- Add documentation for theme creation
- Update settings UI to display theme previews and metadata

Questions for Discussion

Should we implement a theme validation system?
Do we need a theme marketplace or registry?
How should we handle theme updates and versioning?
Should we add theme hot-reloading for development?
Next Steps
[ ] Implementation approval
[ ] Create basic theme documentation
[ ] Implement backend changes
[ ] Update frontend theme system
[ ] Create example themes
[ ] Add theme development documentation
Thoughts? Feedback welcome!

**Comment by timothycarambat** [comment]
@scottybo Is the screenshot via CSS overrides alone? Or are you injecting JS into the page as well?

**Comment by scottybo** [comment]
@timothycarambat all via CSS. It's a little bit hacky as there aren't too many id's or classes to select. 

You might be wondering why I don't create a fork, and the main reason is that maintaining a fork (especially across multiple clients) takes up time / resources. From my perspective, I'd much rather invest that time in extending AnythingLLM itself (in a way that works for you guys, and the larger community).

My initial thoughts are to have an "alpha" release which simply gives the ability to load a different theme, with the clear message that theming isn't currently easy. A beta release might mean we (DCS) submit pull requests to add in ids and classes into the HTML structure so that it becomes easier to theme.

A release candidate might include the ability to upload a zip file via the back-end to install a theme.

But right now, just giving us the ability to easily modify the look and feel would be a huge step forward, even if it is a little bit hacky.

```css

.bg-theme-bg-sidebar {
    padding: 0;
}

[data-theme="light"] {
    --theme-loader: #000000;

    --theme-bg-primary: #fffbf5;
    --theme-bg-secondary: #fffbf5;
    --theme-bg-sidebar: #fffbf5;
    --theme-bg-container: #fffbf5;

    --theme-bg-chat: #ffffff;
    --theme-bg-chat-input: #eaeaea;
    --theme-text-primary: #000;
    --theme-text-secondary: #282828;
    --theme-sidebar-item-default: #fffbf5;
    --theme-sidebar-item-selected: #fffbf5;
    --theme-sidebar-item-hover: #fffbf5;

    --theme-sidebar-item-text-inactive: #000000;
    --theme-sidebar-item-text-active: #ffffff;

    --theme-sidebar-item-workspace-active: #000000;
    --theme-sidebar-item-workspace-inactive: #7a7d7e;

    --theme-sidebar-subitem-default: transparent;
    --theme-sidebar-subitem-selected: #fffbf5;
    --theme-sidebar-thread-selected: #ffffff;
    --theme-sidebar-subitem-hover: #fffbf5;
    --theme-sidebar-border: #fffbf5;

    --theme-sidebar-footer-icon: #ffffff;
    --theme-sidebar-footer-icon-fill: #6e6f6f;
    --theme-sidebar-footer-icon-hover: #d8d6d6;

    --theme-chat-input-border: #000000;
    --theme-action-menu-bg: #eaeaea;
    --theme-action-menu-item-hover: rgba(0, 0, 0, 0.1);
    --theme-settings-input-bg: #ffffff;
    --theme-settings-input-placeholder: rgba(0, 0, 0, 0.5);
    --theme-settings-input-active: rgb(0 0 0 / 0.2);
    --theme-settings-input-text: #000000;
    --theme-modal-border: #d3d3d3;

    --theme-button-primary: #000000;
    --theme-button-primary-hover: #ffffff;

    --theme-file-row-even: #f5f5f5;
    --theme-file-row-odd: #e9e9e9;
    --theme-file-row-selected-even: #0ba5ec;
    --theme-file-row-selected-odd: #0ba5ec;
    --theme-file-picker-hover: #e2e7ee;
}

/*[data-theme="light"] html,body{
    background-color: var(--theme-bg-container);
}*/

.bg-theme-bg-sidebar {
    padding: 0;
}

/** Because there are no ids of selectors we can use to identify that we're on the login page, we instead use the :has selector to see if the root element has an input with the name "username" 

From here we can then target containers within the root element to change the styles of the login page .*/

#root:has(input[name="username"]) > div > div:nth-child(1) {
    display: none;
}
#root:has(input[name="username"]) > div > div:nth-child(2) {
    display: none;
}

/* Logo */
#root:has(input[name="username"]) img {
    position: unset !important;
    max-width: 200px;
}

#root:has(input[name="username"]) form {
    margin-top: 20px;
    padding: 2rem;
}

#root:has(input[name="username"]) form > div {
    margin-top: 20px;
    border-radius: 2rem;
    padding: 1rem;
}

/* Hide the "Welcome to" text */
#root:has(input[name="username"]) form p {
    color: var(--theme-text-primary);
}

/* Chat Window */

div#chat-history {
    margin: 0 auto;
}

[role="presentation"] {
    background-color: var(--theme-bg-primary);
}

[role="presentation"] .bg-theme-bg-chat:nth-child(odd), [role="presentation"] .bg-theme-bg-chat:nth-child(even) {
    max-width: 800px;
    margin: 0 auto;
}

[role="presentation"] .bg-theme-bg-chat:nth-child(odd) {
    background-color: #f2e8d8;
    border-radius: 2rem;
    margin: 0 3rem;
    width: auto;
    padding: 0;
    flex-direction: row;
    justify-content: space-between;
}

[role="presentation"] .bg-theme-bg-chat:nth-child(even) {
    margin: 0 3rem;
    width: auto;
    padding: 0;
    flex-direction: row;
    justify-content: space-between;
}

[role="presentation"] .bg-theme-bg-chat {
    background-color: var(--theme-bg-primary);
}

[role="presentation"] .bg-theme-bg-chat:nth-child(odd) > div {
    width: 100% !important;
    padding: 1rem 2rem;
}

[role="presentation"] .bg-theme-bg-chat:nth-child(odd) > div > div {
    padding: 0;
}

[role="presentation"] .bg-theme-bg-chat:nth-child(even) {
    width: 100% !important;
    padding: 0;
}

/* Forms */
select, input, textarea, .bg-theme-settings-input-bg {
    border: 1px solid var(--theme-chat-input-border) !important;
}

/* Sidebar Workspaces */
.light .light\:bg-\[\#C2E7FE\] {
    --tw-bg-opacity: 1;
    background-color: black;
    color: white;
}

.light .light\:bg-\[\#C2E7FE\]\/90 {
    background-color: black;
    color: white;
}

.light .light\:bg-\[\#E0F2FE\] {
    --tw-bg-opacity: 1;
    background-color: black;
    color: white;
}

.light .light\:bg-\[\#e5e7eb\] {
    --tw-bg-opacity: 1;
    background-color: black;
    color: white;
}

.light .light\:bg-black {
    --tw-bg-opacity: 1;
    background-color: black;
    color: white;
}

.light .light\:bg-black\/10 {
    background-color: black;
    color: white;
}

.light .light\:bg-blue-100 {
    --tw-bg-opacity: 1;
    background-color: black;
    color: white;
}

.text-sidebar {
    --tw-text-opacity: 1;
    color: white;
}

.bg-theme-bg-sidebar [role="listitem"] {
    
    
}

.bg-theme-sidebar-item-default {
    padding: 0 !important;
}

/* Selected Workspace */
.bg-theme-sidebar-item-selected {
    border-top: 0;
    border-right: 0;
    border-left: 0;
    border-bottom: 1px solid black;
    border-radius: 0;
    border-color: black !important;
}

.bg-theme-bg-sidebar [aria-label="Threads"] {
    border-bottom: 1px solid black;
    margin-bottom: 1rem;
    flex-direction: column-reverse;
    display: flex;
    overflow-x: scroll;
    max-height: 300px;
    background: white;
}
.bg-theme-bg-sidebar [aria-label="Threads"] > div:has(a p:contains("default")) {
    order: 99999; /* Moves "default" button above the other buttons */
}

.bg-theme-bg-sidebar [aria-label="Threads"] > div {
    
}

.bg-theme-bg-sidebar .w-\[130px\] {
    width: auto !important;
}

.bg-\[var\(--theme-sidebar-thread-selected\)\] {
    border: unset !important;
}

.bg-\[var\(--theme-sidebar-thread-selected\)\] a > p {
    font-weight: bold !important;
}

.bg-theme-sidebar-item-selected > div > div > svg, .bg-theme-sidebar-item-default > div > div > svg  {
    display: none;
}

.hover\:bg-theme-sidebar-subitem-hover:hover {
    background-color: var(--theme-sidebar-subitem-hover);
}
```
