### ISSUE TITLE
[ERROR+SOLUTION]: Unable to Enable Multi-User Mode

### ISSUE THREAD

**Issue by JOduMonT** [Mintplex-Labs/anything-llm#3257]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Hi;

I had this error before; mostly everytime I spin a new anythingllm instance

It is probably an error with my user rights in `:/app/server/storage`
in my docker-compose I left that note:
````
## ensure `chown 1000:100` + `chmod g+w` for \`/app/server/storage`
````
which saddly doesnt help me at all

### the error is:
Failed to enable Multi-User mode: Unexpected token 'l', "Internal S" is not valid JSON
![Image](https://github.com/user-attachments/assets/b2f60416-984c-4a21-b7e4-eb212083fb19)

### How do I spin my AnythingLLM
1. I simply carry over my docker-compose.yml
````
---
services:
  anythingllm:
    cap_add:
    - SYS_ADMIN
    container_name: anythingllm
    env_file:
    - ../env/anythingllm
    image: mintplexlabs/anythingllm
    restart: always
    volumes:
    - ../env/anythingllm:/app/server/.env
    ## ensure `chown 1000:100` + `chmod g+w` for `/app/server/storage`
    - ../data/anythingllm:/app/server/storage
````
2. create `../data/anythingllm`
3. chown and chmod `../data/anythingllm`
then that create `anythingllm.db`, `comkey` and `plugins` in `../data/anythingllm/`

#### Why no port are declared ?
- because I use a docker proxy which connect internally and directly to `http://anythingllm:3001`

### Which VectorDB?
- qdrant

### What are the logs are saying?
doh!
I found it
````
error: EACCES: permission denied, open '/app/server/.env' Error: EACCES: permission denied, open '/app/server/.env'
````

## SOLUTION
chown and chmod `/app/server/.env` too ;)

### So Why ?
Why I'm still posting my Bug issue if I found the solution ?
To help my future me, and other :P
