### ISSUE TITLE
[BUG]: When deploying AnythingLLM using docker-compose.yml and accessing directly on port 3001 without using an Nginx proxy, the error message 'Could not respond to message. An error occurred while streaming response. network error'

### ISSUE THREAD

**Issue by showcup** [Mintplex-Labs/anything-llm#3310]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?
When deploying AnythingLLM using docker-compose.yml and accessing directly on port 3001 without using an Nginx proxy, the error message 'Could not respond to message. An error occurred while streaming response. network error'

**docker-compose.yml**
```yaml
version: '3.8'
services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    ports:
    - "3001:3001"
    cap_add:
      - SYS_ADMIN
    user: "${UID}:${GID}"
    environment:
    # Adjust for your environment
      - STORAGE_DIR=/app/server/storage
    env_file:
      - .env
    volumes:
      - ./data:/app/server/storage
      - ./.env:/app/server/.env
    restart: always
    networks:
      - anything-llm
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  anything-llm:
    driver: bridge
```
**.env**
```
LLM_PROVIDER='ollama'
EMBEDDING_MODEL_PREF='nomic-embed-text:latest'
OLLAMA_BASE_PATH='http://192.168.31.2:11434'
OLLAMA_MODEL_PREF='deepseek-r1:7b'
OLLAMA_MODEL_TOKEN_LIMIT='4096'
EMBEDDING_ENGINE='ollama'
EMBEDDING_BASE_PATH='http://192.168.31.2:11434'
EMBEDDING_MODEL_MAX_CHUNK_LENGTH='8192'
JWT_SECRET='make this a large list of random numbers and letters 20+'
STORAGE_DIR='/app/server/storage'
```

**Error screenshot**

![Image](https://github.com/user-attachments/assets/9135aa96-77e8-49b6-9007-94d2b0375007)
