### ISSUE TITLE
Abnormal shutdown of anythingllm causes data loss

### ISSUE THREAD

**Issue by ayers-ltd** [Mintplex-Labs/anything-llm#3813]
Use docker compose down to restart the application. No data is lost. However, after the virtual machine is forced to shut down, docker will automatically start and find that the data in the anythingllm working directory is lost. Where can I configure it to take a scheduled snapshot or abnormal shutdown without causing data loss?

**Comment by ayers-ltd** [comment]
my docker-compose.yml
```
services:
  anythingllm:
    image: anythingllm-anything-llm:v5
    container_name: anythingllm
    ports:
    - "3001:3001"
    cap_add:
      - SYS_ADMIN
    environment:
    # Adjust for your environment
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET="make this a large list of random numbers and letters 20+"
      # - LLM_PROVIDER=ollama
      - LLM_PROVIDER=volcdeepseek
      - OLLAMA_BASE_PATH=http://127.0.0.1:11434
      - OLLAMA_MODEL_PREF=llama2
      - OLLAMA_MODEL_TOKEN_LIMIT=4096
      # - EMBEDDING_ENGINE=ollama
      # - EMBEDDING_BASE_PATH=http://127.0.0.1:11434
      # - EMBEDDING_MODEL_PREF=nomic-embed-text:latest
      # - EMBEDDING_MODEL_MAX_CHUNK_LENGTH=8192
      - VECTOR_DB=lancedb
      - WHISPER_PROVIDER=local
      - TTS_PROVIDER=native
      - PASSWORDMINCHAR=8
      # Add any other keys here for services or settings
      # you can find in the docker/.env.example file
    volumes:
      - anythingllm_storage:/app/server/storage
    restart: always

volumes:
  anythingllm_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/anythingllm-xb/data

```
