### ISSUE TITLE
[BUG]: Docker container doesn't start

### ISSUE THREAD

**Issue by olegshulyakov** [Mintplex-Labs/anything-llm#3856]
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

Container does not start. There is an error in logs related to database location:

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "anythingllm.db" at "file:../storage/anythingllm.db"
Error: Schema engine error:
SQLite database error
unable to open database file: ../storage/anythingllm.db
```

### Are there known steps to reproduce?

Tried to deploy application to Docker with Docker Compose

```yml
services:
  anything-llm:
    image: mintplexlabs/anythingllm:latest
    container_name: anything-llm
    restart: on-failure:5
    mem_limit: 2g
    mem_reservation: 128M
    healthcheck:
      test: curl -f http://localhost:3001 || exit 1
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - STORAGE_DIR=/app/server/storage
    volumes:
      - "${FOLDER_FOR_DATA}/anything-llm:/app/server/storage"
    ports:
      - "${WEBUI_PORT_ANYTHING_LLM}:3001"
```
