### ISSUE TITLE
[BUG]: Stuck loading on upload documents module

### ISSUE THREAD

**Issue by Milor123** [Mintplex-Labs/anything-llm#3912]
### How are you running AnythingLLM?

Docker (local)

### What happened?

![Image](https://github.com/user-attachments/assets/72d25d28-7ee6-4c44-8f55-59ea4431a08b)

I am using image: mintplexlabs/anythingllm in windows 11 wsl2 with version anythingllm v1.8.1

I was using Milvus but I've tested switch to Lance, but i got the same result, infinite loading

I'm not sure what happened, it had been working before without any problem, I don't even know when it went wrong.

Docker error log on anythingllm
```bash
[backend] error: Cannot read properties of null (reading 'startsWith') TypeError: Cannot read properties of null (reading 'startsWith')

    at Object.canWatch (/app/server/models/documentSyncQueue.js:56:21)

    at fileToPickerData (/app/server/utils/files/index.js:365:25)

    at async Promise.all (index 0)

    at async viewLocalFiles (/app/server/utils/files/index.js:64:23)

    at async /app/server/endpoints/system.js:419:28

[backend] error: Cannot read properties of null (reading 'startsWith') TypeError: Cannot read properties of null (reading 'startsWith')

    at Object.canWatch (/app/server/models/documentSyncQueue.js:56:21)

    at fileToPickerData (/app/server/utils/files/index.js:365:25)

    at async Promise.all (index 0)

    at async viewLocalFiles (/app/server/utils/files/index.js:64:23)

    at async /app/server/endpoints/system.js:419:28
```

### Are there known steps to reproduce?

Open AnythingLLM
Try open the upload panel
Stuck loading

Then I've tried reboot containers, change milvus to Lance, and it keep stucked loading.

**Comment by Milor123** [comment]
> How is the Docker volume configured?
> 
> https://docs.anythingllm.com/installation-docker/local-docker

this is my docker-compose.yml file, i am in **windows 11**, is it bad? 

```yaml
services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    ports:
    - "3001:3001"
    cap_add:
      - SYS_ADMIN
    environment:
    # Adjust for your environment
      - STORAGE_DIR=/app/server/storage
    restart: always
    volumes:
     #I use this directory because in old time (1 year ago or more) I was migrating from desktop version to docker.
      -  C:\Linux\Linux-conf\anythingllm-desktop\sslcert/:/app/server/sslcert/
      -  C:\Linux\Linux-conf\anythingllm-desktop\:/app/server/storage
      -  C:\Linux\Linux-conf\anythingllm-desktop\.env:/app/server/.env
      -  C:\Linux\Linux-conf\anythingllm-desktop\hotdir:/app/collector/hotdir

    extra_hosts:
      - "host.docker.internal:host-gateway"

```
