### ISSUE TITLE
[BUG]: Weaviate integration not working

### ISSUE THREAD

**Issue by dblinick** [Mintplex-Labs/anything-llm#896]
### How are you running AnythingLLM?

Docker (local)

### What happened?

Getting error when using Weaviate as vector store: 
![image](https://github.com/Mintplex-Labs/anything-llm/assets/14971287/b92126f1-b8a3-4fc0-b078-69fd787ceb99)

Storage of document is working (I can see it in the weaviate logs when I store a doc) - but it looks like whatever function is supposed to call weaviate is failing (I don't even see it connect on the weaviate side).

Here is the error from the docker logs: 
`anything-llm  | TypeError: Cannot read properties of null (reading 'map')
anything-llm  |     at Object.similarityResponse (/app/server/utils/vectorDbProviders/weaviate/index.js:93:45)
anything-llm  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
anything-llm  |     at async Object.performSimilaritySearch (/app/server/utils/vectorDbProviders/weaviate/index.js:366:47)
anything-llm  |     at async streamChatWithWorkspace (/app/server/utils/chats/stream.js:110:9)
anything-llm  |     at async /app/server/endpoints/chat.js:84:9`

Docker image was pulled today using :latest

**Comment by shatfield4** [comment]
How are you using Weaviate? Their cloud hosted version or local version? I have just tested this using their cloud hosted version and cannot replicate this bug. Also which embedding provider are you using?

**Comment by dblinick** [comment]
Hi Sean,
I am using the locally hosted version (docker) - I don't have access to my machine at the moment to check the specific version, but will update this thread when i do.  Embeddings are being done by ollama (nomic-embed-text) - work fine with lancedb - and as mentioned previously - i don't get any errors when the files embed.

**Comment by timothycarambat** [comment]
Trying to replicate:
`docker pull cr.weaviate.io/semitechnologies/weaviate:1.24.2`
```yaml
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.2
    ports:
    - 8080:8080
    - 50051:50051
    restart: on-failure:0
```
Weaviate is confirmed running at `http://localhost:8080`

`docker compose up -d`

`docker pull mintplexlabs/anythingllm`

In AnythingLLM, Weaviate connection is input as `http://host.docker.internal:8080` due to loopback in the container and Weaviate running on host network.
- Use OpenAI as LLM, default embedder.
- I create a new workspace
- Upload a document
- Embed document
- Send query. Got response back with citations
